const translations={
de:{navAbout:"Über mich",navJourney:"Mein Weg",navGallery:"Galerie",navContact:"Kontakt",eyebrow:"FITNESS • DISZIPLIN • LIFESTYLE",heroTitle:"Baue deinen Körper.<br><em>Baue dich selbst.</em>",heroCopy:"Eine persönliche Fitness-Reise – mit Fokus auf Beständigkeit, Energie und einem starken Mindset.",discover:"Meine Reise entdecken",viewPhotos:"Fotos ansehen",aboutEyebrow:"ÜBER PAVLOS",aboutTitle:"Fitness ist mehr als Aussehen.",aboutText:"Für mich bedeutet Training Disziplin, Selbstvertrauen und jeden Tag eine stärkere Version von mir selbst zu werden.",stat1:"Mindset",stat2:"Beständigkeit",stat3:"Fortschritt",statementEyebrow:"DAS MINDSET",statementTitle:"Keine Abkürzungen.<br><span>Nur Arbeit.</span>",statementText:"Kleine Entscheidungen, jeden Tag wiederholt, werden zu einem Lebensstil.",journeyEyebrow:"MEIN ANSATZ",journeyTitle:"Die Getfit-Reise",journeyCopy:"Hart trainieren, gut regenerieren, bewusst essen und immer weitergehen.",card1Title:"Training",card1Text:"Kraft, Bewegung und Einheiten, die den Körper herausfordern.",card2Title:"Ernährung",card2Text:"Einfaches Essen, gute Energie und ein nachhaltiger Ansatz.",card3Title:"Lifestyle",card3Text:"Selbstvertrauen, Regeneration und Gewohnheiten für den Alltag.",galleryEyebrow:"ECHTE MOMENTE",galleryTitle:"Der Lifestyle",galleryCopy:"Momente aus der Reise.",ctaEyebrow:"WEITER GEHEN",ctaTitle:"Dein nächstes Level beginnt heute.",ctaText:"Folge der Reise und bleib verbunden.",backTop:"Nach oben ↑"},
fa:{navAbout:"درباره من",navJourney:"مسیر من",navGallery:"گالری",navContact:"ارتباط",eyebrow:"فیتنس • انضباط • سبک زندگی",heroTitle:"بدنت را بساز.<br><em>خودت را بساز.</em>",heroCopy:"یک مسیر شخصی در فیتنس؛ با تمرکز روی استمرار، انرژی و ذهنیت قوی.",discover:"مسیر من",viewPhotos:"دیدن عکس‌ها",aboutEyebrow:"درباره پاولوس",aboutTitle:"فیتنس فقط ظاهر نیست.",aboutText:"برای من تمرین یعنی نظم، اعتمادبه‌نفس و تبدیل شدن به نسخه‌ای قوی‌تر از خودم، هر روز.",stat1:"ذهنیت",stat2:"استمرار",stat3:"پیشرفت",statementEyebrow:"ذهنیت",statementTitle:"میان‌بُری نیست.<br><span>فقط تلاش.</span>",statementText:"تصمیم‌های کوچک که هر روز تکرار می‌شوند، تبدیل به سبک زندگی می‌شوند.",journeyEyebrow:"روش من",journeyTitle:"مسیر Getfit",journeyCopy:"سخت تمرین کن، خوب ریکاوری کن، آگاهانه غذا بخور و همیشه جلو برو.",card1Title:"تمرین",card1Text:"قدرت، حرکت و تمرین‌هایی که بدن را به چالش می‌کشند.",card2Title:"تغذیه",card2Text:"غذای ساده، انرژی خوب و روشی قابل‌دوام.",card3Title:"سبک زندگی",card3Text:"اعتمادبه‌نفس، ریکاوری و عادت‌هایی که در زندگی واقعی جواب می‌دهند.",galleryEyebrow:"لحظه‌های واقعی",galleryTitle:"سبک زندگی",galleryCopy:"مجموعه‌ای از لحظه‌های این مسیر.",ctaEyebrow:"ادامه بده",ctaTitle:"سطح بعدی تو از امروز شروع می‌شود.",ctaText:"این مسیر را دنبال کن و همراه بمان.",backTop:"بازگشت به بالا ↑"},
en:{navAbout:"About",navJourney:"Journey",navGallery:"Gallery",navContact:"Contact",eyebrow:"FITNESS • DISCIPLINE • LIFESTYLE",heroTitle:"Build the body.<br><em>Build yourself.</em>",heroCopy:"A personal fitness journey built around consistency, energy and a strong mindset.",discover:"Discover my journey",viewPhotos:"View photos",aboutEyebrow:"ABOUT PAVLOS",aboutTitle:"Fitness is more than a look.",aboutText:"For me, training is about discipline, confidence and becoming a stronger version of myself — one day at a time.",stat1:"Mindset",stat2:"Consistency",stat3:"Progress",statementEyebrow:"THE MINDSET",statementTitle:"No shortcuts.<br><span>Just work.</span>",statementText:"Small decisions repeated every day become a lifestyle.",journeyEyebrow:"MY APPROACH",journeyTitle:"The Getfit journey",journeyCopy:"Train hard, recover well, eat with purpose and keep moving forward.",card1Title:"Training",card1Text:"Strength, movement and sessions that challenge the body.",card2Title:"Nutrition",card2Text:"Simple food, good energy and a sustainable approach.",card3Title:"Lifestyle",card3Text:"Confidence, recovery and habits that work in real life.",galleryEyebrow:"REAL MOMENTS",galleryTitle:"The lifestyle",galleryCopy:"A collection of moments from the journey.",ctaEyebrow:"KEEP GOING",ctaTitle:"Your next level starts today.",ctaText:"Follow the journey and stay connected.",backTop:"Back to top ↑"}};

let currentLang=localStorage.getItem("pavlosLang")||"de";
function setLang(lang){currentLang=lang;localStorage.setItem("pavlosLang",lang);document.documentElement.lang=lang;document.body.dir=lang==="fa"?"rtl":"ltr";document.getElementById("langBtn").textContent=lang.toUpperCase();document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.innerHTML=translations[lang][k]});document.getElementById("langPanel").classList.remove("open")}
setLang(currentLang);
document.getElementById("langBtn").onclick=()=>document.getElementById("langPanel").classList.toggle("open");
document.querySelectorAll("#langPanel button").forEach(b=>b.onclick=()=>setLang(b.dataset.lang));
document.getElementById("menuBtn").onclick=()=>document.querySelector(".desktop-nav").classList.toggle("mobile-open");
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.12});
document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
window.addEventListener("scroll",()=>{const h=document.documentElement.scrollHeight-innerHeight;document.querySelector(".progress").style.width=(scrollY/h*100)+"%"});
document.getElementById("year").textContent=new Date().getFullYear();
document.querySelectorAll(".photo img").forEach(img=>img.addEventListener("click",()=>{document.getElementById("lightboxImg").src=img.src;document.getElementById("lightbox").classList.add("open")}));
document.getElementById("closeLightbox").onclick=()=>document.getElementById("lightbox").classList.remove("open");
document.getElementById("lightbox").onclick=e=>{if(e.target.id==="lightbox")e.currentTarget.classList.remove("open")};